name: ✨ 새로운 기능 제안
description: 프로젝트에 추가되었으면 하는 기능을 제안합니다.
labels: [기능제안]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 아이디어를 제안해 주셔서 감사합니다 🙌  
        자세하게 작성해주실수록 반영 가능성이 높아집니다!

  - type: input
    id: context
    attributes:
      label: 어떤 문제를 해결하고 싶으신가요?
      description: 이 기능이 왜 필요한지 간단히 설명해주세요.
      placeholder: "현재 불편한 점 또는 해결하고자 하는 문제"

  - type: textarea
    id: proposal
    attributes:
      label: 제안하는 기능 설명
      description: 기능의 작동 방식이나 기대하는 동작을 구체적으로 작성해주세요.
      placeholder: "사용자 입장에서 기능이 어떻게 작동하는지 설명해주세요."

  - type: textarea
    id: alternatives
    attributes:
      label: 고려해본 다른 방법이 있나요?
      description: 비슷한 기능이나 접근법이 있다면 함께 공유해주세요 (선택)
      placeholder: "다른 접근 방식이 있다면 비교해주세요."
