name: ❓ 질문 또는 문의
description: 라이브러리 사용 중 궁금한 점이나 문의사항을 남겨주세요.
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        질문해 주셔서 감사합니다!  
        가능한 빠르게 답변드릴 수 있도록 아래 항목을 작성해주세요 🙇‍♂️

  - type: input
    id: version
    attributes:
      label: 사용 중인 라이브러리 버전
      placeholder: "예: v1.2.3"

  - type: textarea
    id: question
    attributes:
      label: 질문 내용
      description: 최대한 자세히 질문 내용을 작성해주세요.
      placeholder: "무엇을 하고 싶었고, 어떤 문제에 부딪혔는지 설명해주세요."

  - type: textarea
    id: code
    attributes:
      label: 관련 코드나 설정
      render: typescript
      optional: true
